# Generated by Django 3.2.9 on 2021-12-17 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=140),
        ),
    ]
